import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import NavigationBar from "./_contentBlocks/NavigationBar";
import Footer from "./_contentBlocks/Footer";
import { TanstackQueryProvider } from "./_providers/TanstackQueryProvider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <TanstackQueryProvider>
            <main>{children}</main>
            <Toaster />
          </TanstackQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
