import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import NavigationBar from "./_contentBlocks/NavigationBar";
import Footer from "./_contentBlocks/Footer";
import { TanstackQueryProvider } from "./_providers/TanstackQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TanstackQueryProvider>
          <NavigationBar />
          <main>{children}</main>
          <Footer />
          <Toaster />
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
