export const counties = [
  { name: "Nairobi", rating: 1 },
  { name: "Kiambu", rating: 2 },
  { name: "Kajiado", rating: 2 },
  { name: "Machakos", rating: 2 },
  { name: "Murang'a", rating: 2 },
  { name: "Kirinyaga", rating: 3 },
  { name: "Nyandarua", rating: 3 },
  { name: "Nakuru", rating: 3 },
  { name: "Embu", rating: 3 },
  { name: "Makueni", rating: 3 },
  { name: "Kitui", rating: 3 },
  { name: "Laikipia", rating: 4 },
  { name: "Meru", rating: 4 },
  { name: "Tharaka-Nithi", rating: 4 },
  { name: "Nyeri", rating: 4 },
  { name: "Narok", rating: 4 },
  { name: "Kericho", rating: 4 },
  { name: "Bomet", rating: 4 },
  { name: "Samburu", rating: 5 },
  { name: "Isiolo", rating: 5 },
  { name: "Baringo", rating: 5 },
  { name: "Elgeyo-Marakwet", rating: 5 },
  { name: "Trans-Nzoia", rating: 5 },
  { name: "Uasin Gishu", rating: 5 },
  { name: "Nandi", rating: 5 },
  { name: "Marsabit", rating: 6 },
  { name: "Taita-Taveta", rating: 6 },
  { name: "West Pokot", rating: 7 },
  { name: "Turkana", rating: 7 },
  { name: "Lamu", rating: 9 },
  { name: "Tana River", rating: 9 },
  { name: "Kwale", rating: 9 },
  { name: "Kilifi", rating: 9 },
  { name: "Mombasa", rating: 9 },
  { name: "Kakamega", rating: 7 },
  { name: "Vihiga", rating: 7 },
  { name: "Bungoma", rating: 7 },
  { name: "Busia", rating: 7 },
  { name: "Kisumu", rating: 7 },
  { name: "Homa Bay", rating: 8 },
  { name: "Migori", rating: 8 },
  { name: "Kisii", rating: 8 },
  { name: "Nyamira", rating: 8 },
  { name: "Siaya", rating: 8 },
  { name: "Garissa", rating: 10 },
  { name: "Wajir", rating: 10 },
  { name: "Mandera", rating: 10 },
];
